# Generated by Django 4.2.30 on 2026-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='ai_insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='insights_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
